#%RAML 1.0
title: happy mall
version: 1.0
description: RESTful APIs of happymall

/manage:
  /user:
    /login:
      description: add login in happymall
      post:
        description: admin login
        queryParameters:
          username:
            type: string
            description: admin name
            required: true
          password:
            type: string
            description: admin password
            required: true
        responses:
          404:
            description: false
            body:
              application/json:
                example:
                  {
                    "status": 1,
                    "msg": "admin login fail"
                  }
          200:
            description: false
            body:
              application/json:
                example:
                  {
                    "status": 0,
                    "msg": "admin login success"
                  }
  /product:
    /addProduct:
      description: add a product
      post:
        description: add product
        queryParameters:
          Product:
            type: Product
            required: true
        responses:
          404:
            description: false
            body:
              application/json:
                example:
                  {
                    "status": 1,
                    "msg": "add product fail"
                  }
          200:
            description: success
            body:
              application/json:
                example:
                  {
                    "status": 0,
                    "msg": "add product success"
                  }
    /setStatus:
      description: update product status
      post:
        description: set product status
        queryParameters:
          Product:
            type: Product
            required: true
        responses:
          404:
            description: false
            body:
              application/json:
                example:
                  {
                    "status": 1,
                    "msg": "update product status fail"
                  }
          200:
            description: success
            body:
              application/json:
                example:
                  {
                    "status": 0,
                    "msg": "update product status success"
                  }
    /getDetail:
      description: get product detail
      get:
        description: get product detail
        queryParameters:
          productId:
            type: integer
            required: true
        responses:
          404:
            description: false
            body:
              application/json:
                example:
                  {
                    "status": 1,
                    "msg": get product detail fail
                  }
          200:
            description: success
            body:
              application/json:
                example:
                  {
                    status: 1,
                    "data": {
                      "id": 2,
                      "categoryId": 2,
                      "parentCategoryId":1,
                      "name": "oppo R8",
                      "subtitle": "oppo促销进行中",
                      "imageHost": "http://img.happymmall.com/",
                      "mainImage": "mainimage.jpg",
                      "subImages": "[\"mmall/aa.jpg\",\"mmall/bb.jpg\",\"mmall/cc.jpg\",\"mmall/dd.jpg\",\"mmall/ee.jpg\"]",
                      "detail": "richtext",
                      "price": 2999.11,
                      "stock": 71,
                      "status": 1,
                      "createTime": "2016-11-20 14:21:53",
                      "updateTime": "2016-11-20 14:21:53"
                    }
                  }
    /getProductList:
      description: get product list
      get:
        description: get product list
        queryParameters:
          pageNum:
            type: integer
          pageSize:
            type: integer
        responses:
          404:
            description: false
            body:
              application/json:
                example:
                  {
                    "status": 1,
                    "msg": "get product list fail"
                  }
          200:
            description:
            body:
              application/json:
                example:
                  {
                    "status": 0,
                    "data": {
                      "pageNum": 1,
                      "pageSize": 10,
                      "size": 2,
                      "orderBy": null,
                      "startRow": 1,
                      "endRow": 2,
                      "total": 2,
                      "pages": 1,
                      "list": [
                        {
                          "id": 1,
                          "categoryId": 3,
                          "name": "iphone7",
                          "subtitle": "双十一促销",
                          "mainImage": "mainimage.jpg",
                          "status":1,
                          "price": 7199.22
                        },
                        {
                          "id": 2,
                          "categoryId": 2,
                          "name": "oppo R8",
                          "subtitle": "oppo促销进行中",
                          "mainImage": "mainimage.jpg",
                          "status":1,
                          "price": 2999.11
                        }
                      ],
                      "firstPage": 1,
                      "prePage": 0,
                      "nextPage": 0,
                      "lastPage": 1,
                      "isFirstPage": true,
                      "isLastPage": true,
                      "hasPreviousPage": false,
                      "hasNextPage": false,
                      "navigatePages": 8,
                      "navigatepageNums": [
                              1
                      ]
                    }
                  }
    /searchProduct:
      description:
      get:
        description: search product
        queryParameters:
          productName:
            type: string
            required: true
          productId:
            type: integer
            required: true
          pageNum:
            type: integer
          pageSize:
            type: integer
        responses:
          404:
            description: false
            body:
              application/json:
                example:
                  {
                    "status": 10,
                    "msg": "user need login"
                  }
          200:
            description:
            body:
              application/json:
                example:
                  {
                    "status": 0,
                    "data": {
                      "pageNum": 1,
                      "pageSize": 10,
                      "size": 1,
                      "orderBy": null,
                      "startRow": 1,
                      "endRow": 1,
                      "total": 1,
                      "pages": 1,
                      "list": [
                        {
                          "id": 1,
                          "categoryId": 3,
                          "name": "iphone7",
                          "subtitle": "双十一促销",
                          "mainImage": "mainimage.jpg",
                          "price": 7199.22
                        }
                      ],
                      "firstPage": 1,
                      "prePage": 0,
                      "nextPage": 0,
                      "lastPage": 1,
                      "isFirstPage": true,
                      "isLastPage": true,
                      "hasPreviousPage": false,
                      "hasNextPage": false,
                      "navigatePages": 8,
                      "navigatepageNums": [
                              1
                      ]
                    }
                  }
  /category:
    /addCategory:
      description: user and a category
      post:
        description: add a category
        queryParameters:
          categoryName:
            type: string
            description: category name
            required: true
          categoryId:
            type: integer
            description: category id
            required: true
        responses:
          404:
            description: false
            body:
              application/json:
                example:
                  {
                    "status": 1,
                    "msg": "user need login"
                  }
          200:
            description: success
            body:
              application/json:
                example:
                  {
                    "status": 1,
                    "msg": "add category success"
                  }
    /updateCategory:
      description: user update category
      post:
        description: update category
        responses:
          404:
            description: false
            body:
              application/json:
                example:
                  {
                    "status": 1,
                    "msg": "user need login"
                  }
          200:
            description: false
            body:
              application/json:
                example:
                  {
                    "status": 0,
                    "msg": "update category success"
                  }
    /getChildrenCategoryId:
      description: user get child category id
      get:
        description: get all child category id
        queryParameters:
          categoryId:
            type: integer
            description: category id
            required: true
        responses:
          404:
            description: false
            body:
              application/json:
                example:
                  {
                    "status": 1,
                    "msg": "user need login"
                  }
          200:
            description:
            body:
              application/json:
                example:
                  {
                    "status": 0,
                    "msg": "get child category id success"
                  }
    /getCategoryId:
      description: get all categories
      get:
        description: get all category
        queryParameters:
          categoryId:
            type: integer
            description: category id
            required: true
        responses:
          404:
            description: false
            body:
              application/json:
                example:
                  {
                    "status": 10,
                    "msg": "need admin authority"
                  }
          200:
            description: success
            body:
              application/json:
                example:
                  {
                    "data": [
                      100009,
                      100010,
                      100001,
                      100006,
                      100007,
                      100008
                      ]
                  }
types:
  Product:
    type: object
    properties:
      id:
        description: product id
        type: integer
      categoryId:
        description: category id
        type: integer
      name:
        description: product name
        type: string
      subtitle:
        description: product title
        type: string
      mainImage:
        description: product main image
        type: string
      subImages:
        description: product sub image
        type: string
      detail:
        description: product detail
        type: string
      price:
        description: product price
        type: object
      stock:
        description: product stock
        type: integer
      status:
        description: product status
        type: integer


